version: '3'
services:
    zk1:
        image: zk-image
        container_name: zk1
        build:
         context: .
         dockerfile: Dockerfile.zk
        restart: always
        hostname: zk1
        ports:
            - "2181:2181"
        environment:
            ZK_ID: 1
        volumes:
          - ./zk1.cfg:/zk1/zk1.cfg

    zk2:
        image: zk-image
        container_name: zk2
        build:
         context: .
         dockerfile: Dockerfile.zk
        restart: always
        hostname: zk2
        ports:
            - "2182:2181"
        environment:
            ZK_ID: 2
        volumes:
          - ./zk2.cfg:/zk2/zk2.cfg

    zk3:
        image: zk-image
        container_name: zk3
        build: 
         context: .
         dockerfile: Dockerfile.zk
        restart: always
        hostname: zk3
        ports:
            - "2183:2181"
        environment:
            ZK_ID: 3
        volumes:
          - ./zk3.cfg:/zk3/zk3.cfg

    kafka1:
        image: my-kafka:latest
        container_name: kafka1
        build:
         context: .
         dockerfile: Dockerfile.kafka
        restart: always
        hostname: kafka1
        ports:
          - "9091:9092"
        depends_on:
          - zk1
          - zk2
          - zk3
        environment:
          BROKER_ID: 1
          ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - ./kafka.properties:/broker/kafka.properties

    kafka2:
        image: my-kafka:latest
        container_name: kafka2
        build:
         context: .
         dockerfile: Dockerfile.kafka
        restart: always
        hostname: kafka2
        ports:
          - "9092:9092"
        depends_on:
          - zk1
          - zk2
          - zk3
        environment:
          BROKER_ID: 2
          ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - ./kafka.properties:/broker/kafka.properties

    kafka3:
        image: my-kafka:latest
        container_name: kafka3
        build:
         context: .
         dockerfile: Dockerfile.kafka
        restart: always
        hostname: kafka3
        ports:
          - "9093:9092"
        depends_on:
          - zk1
          - zk2
          - zk3
        environment:
          BROKER_ID: 3
          ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - ./kafka.properties:/broker/kafka.properties

    kafka-manager:
        image: hlebalbau/kafka-manager:latest
        container_name: kafka-manager
        environment:
          ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
          APPLICATION_SECRET: "password"
        logging:
          options:
            max-file: "5"
            max-size: "10m"
        ports:
           - "9000:9000"
        depends_on:
          - zk1
          - zk2
          - zk3
